id: P009276
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:11.468611
source_metadata:
  id: bdr:W13916
  title: སྨྱུང་གནས་ཀྱི་ཆོ་ག
  author: ''
  volumes:
    8653575c915a4f209ced1795923bb0d4:
      image_group_id: I1CZ943
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
