id: IB0E94BE7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:12:38+00:00'
last_modified: '2022-06-08T09:52:06.784949+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W13916
  title: སྨྱུང་གནས་ཀྱི་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EDE5:
      image_group_id: I1CZ943
      title: ''
      total_pages: 58
      order: 1
      base_file: EDE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
